### PR TITLE
check for updated appdata before showing password modal

### LINKED ISSUE #2245: [BUG] Entering incorrect password during expired session when confirming transaction does not throw "incorrect password" error
Reproduction:

- Log onto Freighter extension without needing to enter your password
- initiate a Send
- Enter wrong password
- Pressing "enter" doesn't also trigger "Confirm Send"
- If you enter the wrong password, you get a "transaction failed" error, but it doesn't tell you why the transaction failed.

Intended Behavior:
- Entering an incorrect password should throw an error
- Entering an incorrect password should NOT allow you to proceed, and the "Confirm Send" button should not be clickable.

If your session is still active, it wouldn't ask you for your password here. So it must've been that it was active when you opened but quickly expired

### PR DESCRIPTION
**Pull request by piyalbasu**
Closes #2245 

This fixes 2 related bugs in the send/swap flow:

1. If a user entered the wrong password at the "verify password" stage, the UI didn't confirm the password and it would attempt to sign and submit with an incorrect password. This would of course fail, but just would give a generic "tx failed" msg. Now, the UI properly surfaces an incorrect password message and allows a user to retry

2. If a user's session expired after Freighter had already opened and loaded account details, once the user got to the send tx step, the app would try to sign/submit. This would also fail because the Background script didn't have the password. Now, the UI checks loadAccount once again before showing/hiding the verify modal to make sure everything is in sync

https://github.com/user-attachments/assets/2cddd991-0d70-49d4-af8a-772515ae3d35

### CODE REVIEW

File: extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx [hunk 1]
```diff
@@ -75,22 +79,48 @@ export const SendingTransaction = ({
...
     const getData = async () => {
       await fetchData({
         isSwap,
       });
     };
-    if (!isVerifyAccountModalOpen) {
+    if (
+      submitAccountState.state === RequestState.SUCCESS &&
+      submitAccountState.data.type === AppDataType.RESOLVED &&
+      hasPrivateKey
```
Comment (piyalbasu) [inline extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx:94]: let's make this more deterministic; instead of basing this trigger off of the modal being opened or closed, let's base it off of having re-loaded account info and checking if we have the private key needed

File: extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx [hunk 2]
```diff
@@ -75,22 +79,48 @@ export const SendingTransaction = ({
...
+    };
+    getData();
+    // eslint-disable-next-line react-hooks/exhaustive-deps
+  }, []);
+
+  useEffect(() => {
+    if (
+      submitAccountState.state === RequestState.SUCCESS &&
+      submitAccountState.data.type === AppDataType.RESOLVED &&
+      !submitAccountState.data.hasPrivateKey
```
Comment (piyalbasu) [inline extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx:113]: re-check the hasPrivateKey status and open the modal if needed

File: extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx [hunk 3]
```diff
@@ -75,22 +79,48 @@ export const SendingTransaction = ({
...
+    }
+  }, [submitAccountState]);
 
   const handleConfirm = async (password: string) => {
-    await dispatch(confirmPassword(password));
-    setIsVerifyAccountModalOpen(false);
+    const confirmPasswordResp = await dispatch(confirmPassword(password));
+    if (confirmPassword.fulfilled.match(confirmPasswordResp)) {
+      setIsVerifyAccountModalOpen(false);
+    }
```
Comment (piyalbasu) [inline extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx:123]: don't dismiss the modal until we've properly confirmed

File: extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx [hunk 4]
```diff
@@ -104,6 +134,13 @@ export const SendingTransaction = ({
   const dstAssetIcons =
     destinationAsset !== "native" ? { [destinationAsset]: dstAssetIcon } : {};
 
+  if (
+    submitAccountState.state == RequestState.IDLE ||
+    submitAccountState.state == RequestState.LOADING
+  ) {
+    return <Loading />;
```
Comment (aristidesstaffieri) [inline extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx:141]: Is this loader mean to be centered aligned? It seems like it should be wrapped in a `<View.Content>`

Comment (piyalbasu) [reply extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx:141]: Ah, this component comes with a built-in `<View.Content>`, so it's not necessary here

Freeze-frame on the very brief loading state:

Screenshot 2025-10-08 at 5 38 07 PM

Comment (aristidesstaffieri) [reply extension/src/popup/components/InternalTransaction/SubmitTransaction/index.tsx:141]: oh got it, thanks!
