### PR TITLE
[BUG] SAC token management improvements

### LINKED ISSUE #2220: Add SACs should result in new trustline
### What version are you using?
If you search for an asset by contract address and you add it to your wallet, we will add it is a custom token. This means that we will track the ID manually and not add a trustline.
SACs should be treated as classic assets and a trustline should be added in this case.

### What did you do?
Add any classic asset by contract ID

### What did you expect to see?
Add trustline internal transaction dialog

### What did you see instead?
Add as custom token dialog.

### PR DESCRIPTION
**Pull request by aristidesstaffieri**
Closes #2220 

What
Adds SAC detection during the add/remove token flows. This results in SACs being treated as their classic counterparts(add or remove trustline) in this flow.

Why
When searching for an asset by its SAC address, you are not able to change trust on the token because it was being treated as a custom token.

### CODE REVIEW

File: extension/src/popup/components/manageAssets/ManageAssetRows/index.tsx [hunk 1]
```diff
@@ -79,6 +79,19 @@ export const ManageAssetRows = ({
...
+    if (selectedAsset && selectedAsset.contract) {
+      return isAssetSac(
+        selectedAsset.code,
+        selectedAsset.issuer,
+        selectedAsset.contract,
+        networkDetails.networkPassphrase,
+        networkDetails,
+      );
+    }
+    return true;
```
Comment (aristidesstaffieri) [inline extension/src/popup/components/manageAssets/ManageAssetRows/index.tsx:92]: this is only valid when an asset is selected, so the correct default is `true` by this conditional.

File: extension/src/helpers/__tests__/useGetAssetDomainsWithBalances.test.tsx [hunk 2]
```diff
@@ -27,7 +27,21 @@ jest.mock("@shared/api/helpers/token-list", () => ({
   getCombinedAssetListData: jest.fn().mockResolvedValue([]),
 }));
 jest.mock("popup/helpers/account", () => ({
-  ...jest.requireActual("popup/helpers/account"),
+  sortBalances: (balances: any) => {
```
Comment (piyalbasu) [inline extension/src/helpers/__tests__/useGetAssetDomainsWithBalances.test.tsx:30]: Curious why we need to overwrite the original implementation? This looks pretty similar to the original imp but does not take into account LP's

File: extension/src/popup/components/manageAssets/ManageAssetRows/ChangeTrustInternal/hooks/useChangeTrustData.tsx [hunk 3]
```diff
@@ -52,7 +53,14 @@ function useGetChangeTrustData({
     try {
       const payload = { flaggedKeys: {} } as ChangeTrustData;
 
-      if (!asset.contract) {
+      const isSac = isAssetSac(
```
Comment (piyalbasu) [inline extension/src/popup/components/manageAssets/ManageAssetRows/ChangeTrustInternal/hooks/useChangeTrustData.tsx]: NIT: can we use an object here instead of individual params? A long list of params can get cumbersome if/when we need to add more down the road. 

Also wondering if this can just be `isAssetSac({ asset, networkDetails })`

File: extension/src/popup/components/manageAssets/ManageAssetRows/index.tsx (hunk 1 above)
Comment (piyalbasu) [reply extension/src/popup/components/manageAssets/ManageAssetRows/index.tsx:92]: Mind putting that in as a comment? It'll be helpful for the next dev who comes across this

File: extension/src/helpers/__tests__/useGetAssetDomainsWithBalances.test.tsx (hunk 2 above)
Comment (aristidesstaffieri) [reply extension/src/helpers/__tests__/useGetAssetDomainsWithBalances.test.tsx:30]: our existing mock doesn't actually seem to be including the rest of the file with `requireActual` so it was failing to fetch balances due to missing `sortBalances` function. I mocked it because it's not part of this unit test but Im not sure why the import in that file doesn't see the mock. 🤔

File: extension/src/popup/components/manageAssets/ManageAssetRows/ChangeTrustInternal/hooks/useChangeTrustData.tsx (hunk 3 above)
Comment (aristidesstaffieri) [reply extension/src/popup/components/manageAssets/ManageAssetRows/ChangeTrustInternal/hooks/useChangeTrustData.tsx]: updated in ca3584cd4e94d5f1bed4127ab77bca857d3a8ac4

File: extension/src/helpers/__tests__/useGetAssetDomainsWithBalances.test.tsx (hunk 2 above)
Comment (piyalbasu) [reply extension/src/helpers/__tests__/useGetAssetDomainsWithBalances.test.tsx:30]: Oh that is weird. I wonder if there's some competing mocks colliding or something

**Review by piyalbasu — APPROVED** [review]

File: extension/src/popup/components/manageAssets/ManageAssetRows/index.tsx (hunk 1 above)
Comment (CassioMG) [reply extension/src/popup/components/manageAssets/ManageAssetRows/index.tsx:92]: +1
